services:
  sensors:
    # This 're-injects' the hardware requirements only on your local machine
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - SERIAL_PORT_PATH=/dev/ttyACM0